# [options]
# ; This is the configuration file for the TransitOps Odoo 19 instance
# addons_path = c:/Users/DELL/Downloads/TransitOps/odoo-hackathon-2026/custom_addons,c:/Users/DELL/Downloads/TransitOps/odoo-hackathon-2026/transitops/backend
# admin_passwd = admin
# db_host = localhost
# db_port = 5432
# db_user = odoo
# db_password = odoo
# http_port = 8069
# log_level = info
# ; logfile = c:/Users/THINKPAD/Downloads/TransitOps/odoo.log
[options]
addons_path = C:\Program Files\Odoo 19.0.20260712\server\odoo\addons,C:\Users\DELL\Downloads\TransitOps\odoo-hackathon-2026\custom_addons,C:\Users\DELL\Downloads\TransitOps\odoo-hackathon-2026\transitops\backend
admin_passwd = admin
bin_path = c:\program files\odoo 19.0.20260712\thirdparty
csv_internal_sep = ,
data_dir = C:\Users\DELL\AppData\Local\OpenERP S.A\.Odoo
db_app_name = odoo-{pid}
db_host = localhost
db_maxconn = 64
db_maxconn_gevent = None
db_name = 
db_password = ajee85
db_port = 5432
db_user = ajee
http_port = 8069
limit_memory_soft = 2147483648
limit_time_real = 120
limit_time_real_cron = -1
limit_time_worker_cron = 0
list_db = True
log_level = info
logfile = C:\Program Files\Odoo 19.0.20260712\server\odoo.log
pg_path = c:\program files\odoo 19.0.20260712\postgresql\bin
server_wide_modules = base,rpc,web
with_demo = False
